# Site
name: 'Bruxoativismo'
description: 'Política, Economia, Esportes, Entretenimento, Vida, Saúde, Tecnologia'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'bruxoativismo'
email: 'bruxoativismo@outlook.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
locale: pt-BR

include: ['_pages']
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  luis:
    name: Luís Trindade
    site: https://luishenriquetp.github.io
    avatar: /assets/images/avatar1.jpg
    bio: "Oi, eu sou o Luís, idealizador do projeto Bruxoativismo. Espero poder passar informações úteis e incentivar mais ações conscientes entre bruxos e pagãos!"
    email: bruxoativismo@outlook.com
    twitter: https://twitter.com/luishenriquetp

  jane:
    name: Jane
    site: https://www.wowthemes.net
    avatar: /assets/images/avatar2.jpg
    bio: 'Blogger, fashionista, love to explore new ideas and write on my morning coffee!'
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet

# Defaults
defaults:
  # all posts
  - scope:
      path: '_posts'
    values:
      layout: post
      author: luis
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: '_pages'
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
    vendor,
  ]
